name: Build ML Heating Multiarch

on:
  push:
    tags: ['v*']  # Trigger on ANY version tag
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ml_heating

jobs:
  # Stage 1: Detect release channel from git tag
  detect-release:
    runs-on: ubuntu-latest
    name: Detect Release Channel
    outputs:
      channel: ${{ steps.detect.outputs.channel }}
      version: ${{ steps.detect.outputs.version }}
      is-alpha: ${{ steps.detect.outputs.is-alpha }}
    
    steps:
      - name: Detect channel from git tag
        id: detect
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=${TAG_NAME#v}
          
          if [[ "$VERSION" =~ -alpha\. ]]; then
            echo "channel=alpha" >> $GITHUB_OUTPUT
            echo "is-alpha=true" >> $GITHUB_OUTPUT
            echo "🧪 Alpha release detected: $VERSION"
          else
            echo "channel=latest" >> $GITHUB_OUTPUT
            echo "is-alpha=false" >> $GITHUB_OUTPUT
            echo "🎯 Latest release detected: $VERSION"
          fi
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  # Stage 2: Build Container (Matter Hub Pattern)
  build-container:
    runs-on: ubuntu-latest
    name: Build Container
    needs: [detect-release]
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push multiarch container
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ needs.detect-release.outputs.version }}
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ needs.detect-release.outputs.channel }}
          build-args: |
            BUILD_VERSION=${{ needs.detect-release.outputs.version }}
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            BUILD_REF=${{ github.sha }}
            BUILD_REPOSITORY=${{ github.repository }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Stage 3: Update Add-on Configurations (Simulating Matter Hub Dispatch)
  update-configs:
    runs-on: ubuntu-latest
    name: Update Add-on Configurations
    needs: [detect-release, build-container]
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          
      - name: Update configurations
        run: |
          VERSION="${{ needs.detect-release.outputs.version }}"
          IS_ALPHA="${{ needs.detect-release.outputs.is-alpha }}"
          
          # Install yq for YAML processing
          sudo snap install yq
          
          if [[ "$IS_ALPHA" == "true" ]]; then
            echo "🔧 Updating development addon config to version $VERSION"
            yq eval ".version = \"$VERSION\"" -i ml_heating_dev/config.yaml
            
            echo "Updated ml_heating_dev/config.yaml:"
            grep -E "^(name|version):" ml_heating_dev/config.yaml
          else
            echo "🔧 Updating stable addon config to version $VERSION"
            yq eval ".version = \"$VERSION\"" -i ml_heating/config.yaml
            
            echo "Updated ml_heating/config.yaml:"
            grep -E "^(name|version):" ml_heating/config.yaml
          fi
          
      - name: Commit configuration updates
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          VERSION="${{ needs.detect-release.outputs.version }}"
          IS_ALPHA="${{ needs.detect-release.outputs.is-alpha }}"
          
          # Switch to main branch to avoid detached HEAD
          git checkout main
          
          if [[ "$IS_ALPHA" == "true" ]]; then
            git add ml_heating_dev/config.yaml
            git commit -m "chore: Update development addon to version $VERSION" || exit 0
          else
            git add ml_heating/config.yaml  
            git commit -m "chore: Update stable addon to version $VERSION" || exit 0
          fi
          
          git push origin main

  # Stage 4: Create Release
  release:
    runs-on: ubuntu-latest
    name: Create Release
    needs: [detect-release, build-container, update-configs]
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: ML Heating v${{ needs.detect-release.outputs.version }} ${{ needs.detect-release.outputs.is-alpha == 'true' && '(Alpha)' || '' }}
          body: |
            ## ${{ needs.detect-release.outputs.is-alpha == 'true' && '🧪 ML Heating Control - Alpha Release' || '🎯 ML Heating Control - Stable Release' }}
            
            **Version:** `${{ needs.detect-release.outputs.version }}`  
            **Channel:** `${{ needs.detect-release.outputs.channel }}`  
            **Container:** `${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ needs.detect-release.outputs.channel }}`  
            
            ### Installation
            1. Add this repository to Home Assistant:
               ```
               https://github.com/${{ github.repository }}
               ```
            2. Install **"${{ needs.detect-release.outputs.is-alpha == 'true' && 'ML Heating Control (Development)' || 'ML Heating Control' }}"**
            3. Configure with your Home Assistant entities
            
            ### Container Images (Multiarch: amd64, arm64)
            - `${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ needs.detect-release.outputs.channel }}` (${{ needs.detect-release.outputs.is-alpha == 'true' && 'rolling alpha' || 'latest stable' }})
            - `${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ needs.detect-release.outputs.version }}` (specific version)
            
            ${{ needs.detect-release.outputs.is-alpha == 'true' && '### ⚠️ Alpha Release
            This is an alpha release intended for testing new features. Use with caution in production environments.
            
            **Features:**
            - 🔍 Debug logging enabled
            - 🛠️ Development API enabled  
            - ⚡ Latest features and improvements
            - 🧪 Experimental functionality' || '### 🎯 Stable Release
            This is a production-ready stable release.
            
            **Features:**
            - 🎯 Production-tested configuration
            - 📊 Optimized logging
            - 🔄 Automatic updates enabled
            - 🛡️ Thoroughly validated
            - 📈 Advanced physics-based ML optimization' }}
            
            ### Architecture
            - **Single Multiarch Container**: One image supports all architectures
            - **Tag-based Channels**: `:latest` for stable, `:alpha` for development
            - **Matter Hub Inspired**: Following proven Home Assistant addon patterns
          draft: false
          prerelease: ${{ needs.detect-release.outputs.is-alpha == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
